# time parameters 
dt: 0.0275
startTime: 0.0
warmupTime: 2.0
trainTime: 11.0
testTime: 11.0
errorTime: 1.100

# data generation parameters
system: 'Lorenz_63'
numerical_integrator: 'RK45'

# feature vector parameters
k: 2
s: 1
p: 3

# regression parameters
regression_method: 'ridge'
lambda2: 2.0e-6

# plot parameters
plotPath: 'results/testing/Lorenz63/Lorenz63_ridge_p3.png'

