# basic config file for NGRC.py
# this file is used for code development

# time parameters 
dt: 0.01
startTime: 0.0
warmupTime: 0.5
trainTime: 0.5
testTime: 0.5
errorTime: 0.5

# data generation parameters
system: 'Lorenz_63'
numerical_integrator: 'rk4'

# feature vector parameters
k: 2
s: 1
p: 2

# regression parameters
regression_method: 'ridge'
lambda1: 1.5e-6
lambda2: 1.5e-6
tolerance: 1.0e-7
maxIterations: 200000000

# plot parameters
plotPath: 'results/plot.png'

