# time parameters 
dt: 0.165
startTime: 0.0
warmupTime: 2.0
trainTime: 66
testTime: 66
errorTime: 6.638

# data generation parameters
system: 'Jerk1'
numerical_integrator: 'rk4'

# feature vector parameters
k: 2
s: 1
p: 2

# regression parameters
regression_method: 'ridge'
lambda2: 10.0e-6

# plot parameters
plotPath: 'results/testing/Jerk1/Jerk1_ridge_p2.png'

