#!/bin/bash

# calculates lyapunov exponents and time for the system input (defined in src/lyapunov_time/systems.py)
# input --system, other values have defaults


echo "||"
echo "|| running - find Lyapunov time"
echo "||"
echo ""

python3 src/lyapunov_time/find_lyapunov_time.py --system Lorenz_63

echo ""
echo "||"
echo "|| finished"
echo "||"

